language: python
sudo: false

python:
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly

before_install:
    - pip3 install nose

install:
    - pip3 install -e ./

before_script:
    - true

script:
    - nosetests tests
